import{a as u,S as y,i as c}from"./assets/vendor-CQsNRR_j.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();u.defaults.baseURL="https://pixabay.com/api/";const h="51706817-4b5d2cc21e6cd3f5251979b08";function b(r){return u.get("",{params:{key:h,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})}let d,s;function L(r=[]){let o=document.querySelector("#gallery");o||(o=document.createElement("div"),o.id="gallery",o.classList.add("gallery"),document.body.appendChild(o));const a=r.map(({webformatURL:i,largeImageURL:e,tags:t,likes:n,views:m,comments:p,downloads:g})=>`
      <div class="photo-card">
        <a class="gallery__item" href="${e}">
          <img class="gallery__image" src="${i}" alt="${t}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${n}</li>
          <li><b>Views:</b> ${m}</li>
          <li><b>Comments:</b> ${p}</li>
          <li><b>Downloads:</b> ${g}</li>
        </ul>
      </div>`).join("");o.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new y("#gallery a",{captionsData:"alt",captionDelay:250})}function v(){const r=document.querySelector("#gallery");r&&(r.innerHTML="")}function x(){s||(s=document.createElement("div"),s.classList.add("loader","is-hidden"),s.innerHTML='<span class="loader__spinner"></span>',document.querySelector("form").insertAdjacentElement("afterend",s))}function E(){x(),s.classList.remove("is-hidden")}function S(){s&&s.classList.add("is-hidden")}const f=document.querySelector("form"),l=f.querySelector('button[type="submit"]'),_=l.textContent;f.addEventListener("submit",r=>{r.preventDefault();const a=new FormData(r.target).get("searchText").trim();if(!a){c.error({position:"topRight",title:"Error",message:"Ви нічого не ввели!"});return}v(),E(),l.disabled=!0,l.textContent="Loading...",b(a).then(i=>{const e=i.data.hits;if(!e.length){c.error({position:"topRight",title:"Немає результатів",message:"Нічого не знайдено"});return}L(e)}).catch(i=>{c.error({position:"topRight",title:"Помилка",message:i.message||i})}).finally(()=>{S(),l.disabled=!1,l.textContent=_,r.target.reset()})});
//# sourceMappingURL=index.js.map
